---
# tasks file for zabbix-agent

- name: install
  shell: rpm -Uvh https://repo.zabbix.com/zabbix/5.4/rhel/7/x86_64/zabbix-agent2-5.4.10-1.el7.x86_64.rpm

- name: configure
  shell: sed -i s/Server=127.0.0.1/Server={{zabbix_server}}/g /etc/zabbix/zabbix_agent2.conf

- name: enable
  shell: systemctl enable zabbix-agent2 --now
